import { AppItem, CategoryItem, BlogPost } from './types';

const BASE_CATEGORIES = [
  { name: 'Action', icon: 'Sword' },
  { name: 'Arcade', icon: 'Gamepad2' },
  { name: 'Sports', icon: 'Trophy' },
  { name: 'Video Editor', icon: 'Video' },
  { name: 'Music & Audio', icon: 'Music' },
  { name: 'Social', icon: 'MessageCircle' },
  { name: 'Tools', icon: 'Wrench' },
  { name: 'Productivity', icon: 'Clock' },
  { name: 'Adventure', icon: 'Compass' },
];

export const APPS_DATA: AppItem[] = [
  {
    id: "1",
    name: "CapCut",
    slug: "capcut",
    developer: "Imaanshu N",
    rating: "4.8",
    downloads: "100M",
    size: "298 MB",
    version: "3.5.0",
    category: "Video Editor",
    type: "App",
    updatedAt: "11/07/2026",
    icon: "https://apkgstore.co/wp-content/uploads/2026/06/capcut-video-editor-icon-15093990.png",
    description: "All-in-one video editor with premium effects, modern filters, and professional-level transitions.",
    longDescription: "CapCut is the most downloaded all-in-one free video editor in the world. Designed specifically for content creators on TikTok, Instagram, and YouTube, it allows you to cut, reverse, and change the speed of your clips with absolute precision. This modified premium version (MOD) unlocks all VIP templates, cinematic transitions, advanced color filters, and video export in 4K resolution at 60 FPS without annoying watermarks. In addition, it features a powerful AI-powered automatic subtitle generator to save you hours of manual editing.",
    downloadUrl: "https://www.mediafire.com/file/7wgg623wh4lzmlv/CapCut_MOD_Hub_v27.0.0_%2528Imaanshu_N%2529.apk/file",
    videoUrls: ["https://youtu.be/13dMTwMmpQU?si=GDJ0cD4v9OIlrRkV"], // Converted to array support
    screenshots: [
      "https://play-lh.googleusercontent.com/bVcUMymeJZIxp5p01Ttmc1FHp9Jy501K4lQHB3-OXXSVfNLE6tUa76PY1goZ-O_VBg",
      "https://play-lh.googleusercontent.com/tc7WpgpN90ij7FFkefwBwntXqPdS5TBCk0895Lf5-jB7rPIyz0FdH6OefiWNGlfpDTs",
      "https://play-lh.googleusercontent.com/WfwbtHi4g3vglzS6VgUxeRts_g_wgQ1tSa5DLQl91M4kOoTg8BQFsXi16J4FwIdIKTL_",
      "https://play-lh.googleusercontent.com/6BR---l84afm3uDl0Is1feusM2KO2C_UKek4QNEd70rTRvIa7EgGtBPvl_HVdFyLXg",
      "https://play-lh.googleusercontent.com/iv2O5J96YhJdfKNPZzafkGkrUqphn20Ivbjo0-sJzp6l-HJvrgJjmsknAHNft4DPjA",
      "https://play-lh.googleusercontent.com/lPWAbB_jZycmQg67n7QXxZ2zJRKCZ2lEs7uTwRlRBZIjTuBhJ_9IVsvS85U2BTG3Mhs",
      "https://play-lh.googleusercontent.com/kvAqso_fnZQyheK31RGHZvPhy9UwirOrToD6dYsKiGJo41gQ6OcpxanqB4dG3G2tAQ",
      "https://play-lh.googleusercontent.com/1iL8DEs-fViIMwtJ98yru4PNVgbhK6ndVUe-KwBaC5WVosmk6U_WXYq2Mup0q9K4ZvE",
      "https://play-lh.googleusercontent.com/x4jrQP9_Ev18Cv06R3jGe6pwzRQbL71dN59qnY9M6QYTX6DyEeFQ4LTE7ho6KuA-92L-",
      "https://play-lh.googleusercontent.com/D6F2g22GL-4mRjwAtHLrPmDr64O-4-L_EMsxVxy_K7uZFtTGaEeQKysd3Sx7Y4hxDoM",
      "https://play-lh.googleusercontent.com/V8hd0zQ3-gvG09fe_SijjDuOvhh4UIVox58CfVB-lwkc0RwvpAFLA3yvxTdOD5e3Nw",
      "https://play-lh.googleusercontent.com/V14aFGQw0xuV975eZBiCJfumTJTGEjsOQQx8Gt3LM_cOXh8Pam0UV8lfJiyN5wYJu8cV",
      "https://play-lh.googleusercontent.com/WwhB9aG1IzQoYH1ijHkZ_8z2hyWMc5r718Fm7VW56cvSRLQW9aHXhBjUe2fHfWrT_N_AOepkwBVG3GPsfE6Y"
    ],
    security: {
      checksum: "SHA-256: 9e107d9d372bb6826bd81d3542a419d6",
      secureToken: "Download via verified secure token",
      cloudStorage: "High-speed cloud storage with encrypted access"
    },
    tags: ["MOD", "Free", "No Watermark"],
    isRecommendation: false,
    isRecent: false
  },
  {
    id: "2",
    name: "Subway Surfers",
    slug: "subway-surfers",
    developer: "Imaanshu N",
    rating: "4.7",
    downloads: "1B",
    size: "135 MB",
    version: "3.24.1",
    category: "Arcade",
    type: "Game",
    updatedAt: "10/07/2026",
    icon: "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2023/06/subwaysurf.png&width=160",
    description: "Dodge trains, run at full speed, and escape from the grumpy inspector with unlimited coins.",
    longDescription: "The ultimate endless runner game arrives at Look Mod Store with everything unlocked! Join Jake, Tricky, and Fresh in their exciting escape through the train tracks of the world. This premium MOD version includes infinite gold coins, unlimited resurrection keys, and all premium characters and surfboards unlocked from the first second. Enjoy colorful HD graphics optimized with an ultra-smooth refresh rate. Challenge your friends and dominate the global leaderboards with superior performance.",
    downloadUrl: "https://cdn800.onehost.io/2023/Subway_Surfers_3.66.0_1783939501_latestmodapks.com.apk",
    videoUrls: ["https://youtu.be/o-3sDXTaiEY?si=FZUMMsrE6EkPUrqw"], // Converted to array support
    screenshots: [
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2023/06/Subway-Surfers1.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2023/06/Subway-Surfers2.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2023/06/Subway-Surfers3.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2023/06/Subway-Surfers4.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2023/06/Subway-Surfers5.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2023/06/Subway-Surfers.webp"
    ],
    security: {
      checksum: "SHA-256: a1e87d9d372bc6826bd81d3542a419f1",
      secureToken: "Secure direct download in a single click",
      cloudStorage: "Dedicated premium SYBO servers"
    },
    tags: ["MOD", "Unlimited Coins", "Free"],
    isRecommendation: false,
    isRecent: false
  },
  {
    id: "3",
    name: "Minecraft Pocket Edition",
    slug: "minecraft",
    developer: "Mojang Studios",
    rating: "4.9",
    downloads: "50M",
    size: "620 MB",
    version: "1.21.10",
    category: "Adventure",
    type: "Game",
    updatedAt: "09/07/2026",
    icon: "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2024/08/Minecraft-Pocket-Edition-APK-logo-media.webp&width=160",
    description: "Explore infinite worlds, build anything from the simplest home to the grandest castle.",
    longDescription: "Explore randomly generated worlds and build amazing things, from the simplest homes to the most majestic castles. Play in creative mode with unlimited resources, or delve into survival mode, where you will have to craft weapons and armor to defend yourself against dangerous creatures. Our special MOD version offers you completely free access to all premium aspects of the store, unlocked paid textures, and the ability to play on official multiplayer servers without license verification required.",
    downloadUrl: "https://go.onehost.io/aMacNBG5x6Cr",
    videoUrls: ["https://www.youtube.com/watch?v=MmB9b5njVbA"], // Converted to array support
    screenshots: [
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2024/08/minecraft-pocket-edition-1-media.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2024/08/minecraft-pocket-edition-2-media.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2024/08/minecraft-pocket-edition-3-media.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2024/08/minecraft-pocket-edition-4-media.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2024/08/minecraft-pocket-edition-5-media.webp"
    ],
    security: {
      checksum: "SHA-256: c398e4d372fc5927ad81d3542a419f9",
      secureToken: "License unlocked and clean",
      cloudStorage: "Hosting on distributed premium network"
    },
    tags: ["Paid Subscription Unlocked", "Free", "MOD Menu"],
    isRecommendation: false,
    isRecent: false
  },
  {
    id: "4",
    name: "Spotify Premium",
    slug: "spotify",
    developer: "Imaanshu N",
    rating: "4.8",
    downloads: "500M",
    size: "65 MB",
    version: "8.9.22",
    category: "Music & Audio",
    type: "App",
    updatedAt: "11/07/2026",
    icon: "https://upload.wikimedia.org/wikipedia/commons/2/28/Spotify_Mod.png",
    description: "Listen to millions of songs, albums, and original podcasts without commercial ads.",
    longDescription: "Enjoy the best music and podcasts without limits. With Spotify Premium MOD, you will have the ultimate experience without audio or video advertising interruptions. Unlock the ability to skip songs unlimitedly, play any track you want on-demand with extreme audio quality (320kbps), and activate the music search bar. This version is optimized to consume less battery and RAM, allowing you to browse playlists and artists instantly.",
    downloadUrl: "https://www.mediafire.com/file/lo87s78pkzcpaam/Spotify_signed_MOD_Hub.apk/file",
    videoUrls: ["https://youtu.be/0Wun0877Mrc?si=AfFuVnBZUUqj73sQ",
                "https://youtu.be/ZGwLcs0aot0?si=g-Wmn73gCwNnR1vL",
                "https://youtu.be/UTx5f4M01Wg?si=VcHHIWdQEVXCS0iK"], // Converted to array support
    screenshots: [
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-1-18621311.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-2-18631173.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-3-18633657.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-4-18639279.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-5-18647277.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-6-18641794.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-7-18653171.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-8-18655554.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-9-18665569.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-10-18669538.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-11-18671347.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-12-18679275.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-13-18683660.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-14-18685191.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-15-18692493.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-16-18696317.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-17-18701400.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-18-18707716.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-19-18703505.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-20-18715434.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-21-18717220.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-22-18714212.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-23-18721203.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-24-18726661.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-25-18727195.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-26-18734404.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-27-18735491.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-28-18737849.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-29-18741757.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-30-18748626.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-31-18747327.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-32-18743439.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-33-18759105.jpg",
      "https://apkgstore.co/wp-content/uploads/2025/09/spotify-app-msica-y-podcasts-screenshot-34-18758944.jpg"
    ],
    security: {
      checksum: "SHA-256: f1107d9e102bc6826bd81d3542a419ff",
      secureToken: "High encryption SSL Token",
      cloudStorage: "Ultra-fast global CDN file storage"
    },
    tags: ["MOD", "Premium Unlocked", "Free"],
    isRecommendation: false,
    isRecent: false
  },
  {
    id: "5",
    name: "Brawl Stars",
    slug: "brawl-stars",
    developer: "Supercell",
    rating: "4.6",
    downloads: "100M",
    size: "380 MB",
    version: "55.220",
    category: "Action",
    type: "Game",
    updatedAt: "08/07/2026",
    icon: "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/04/brawl-stars.png&width=160",
    description: "Fast-paced 3v3 multiplayer and mobile battle royale mode with unlocked brawlers.",
    longDescription: "Brawl Stars by Supercell is the action multiplayer game of the moment! Enjoy quick three-minute battles in a variety of exciting game modes. This MOD grants you free unlimited gems, unlimited boxes to open immediately, and spectacular gold skins to show off to all your rivals. Play on a 100% stable private server with automatic matchmaking so you never have to wait to jump into battle.",
    downloadUrl: "https://cdn600.onehost.io/2023/Brawl_Stars_67.264_1777009851_latestmodapks.com.apk",
    videoUrls: ["https://youtu.be/CaryjOdYFa0?si=8K0IEKko45XQ-CrM"], // Converted to array support
    screenshots: [
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/08/brawlstars1.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/08/brawlstars2.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/08/brawlstars3.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/08/brawlstars4.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/08/brawlstars5.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/08/brawlstars6.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/08/brawlstars7.webp",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/08/brawlstars8.webp"
      ],
    security: {
      checksum: "SHA-256: b882e4d372fc5927ad81d3542a4192b3",
      secureToken: "High security anti-ban bypass",
      cloudStorage: "Dedicated Nulls private servers"
    },
    tags: ["MOD", "Unlimited Gems", "Free"],
    isRecommendation: false,
    isRecent: false
  },
  {
    id: "6",
    name: "InstaPro ♚",
    slug: "instapro",
    developer: "Imaanshu N",
    rating: "4.7",
    downloads: "1B",
    size: "173.68 MB",
    version: "15.60.0",
    category: "Social",
    type: "App",
    updatedAt: "05/07/2026",
    icon: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Icon_instapro.png",
    description: "Watch millions of videos from around the world and download videos without watermarks.",
    longDescription: "InstaPro is an advanced modified version of the social media giant. It allows you to download any photo, video, or reel directly to your local gallery without watermarks. In addition, it removes all annoying sponsored ads from the main feed, unlocks high-fidelity media upload quality, and adds special privacy controls to view stories anonymously, hide typing status, and read messages without sending read receipts.",
    downloadUrl: "https://www.mediafire.com/file/rxlkisab413texj/InstaPro-v15.50-look-mod.vercel.app.apk/file?dkey=kq5mibpf2gl&r=1924",
    videoUrls: ["https://youtu.be/ZnT2azDpIA0?si=zZHJkU4VHIMgnlhj"], // Converted to array support
    screenshots: [
      "https://play-lh.googleusercontent.com/hZ2Ob6d0MqLse2lIdNOGgl93H5y82uhX4hC6mWDUpdwK8LjXAunweDQZ6Hocy0riv4KX0lTIzKJz6lhRDV_BiHg=h305",
      "https://play-lh.googleusercontent.com/EvykD5h_-49MNu1JNfAyP0h9xMLceepomvT4DmZgJcy51a6My9G4XjxILgO7LCnEgfYElXY5tWnpmiaZMfMT=h305",
      "https://play-lh.googleusercontent.com/7h2Yo9e9ay8J4Uwt5WkhPCyfLQtI1LzcMbqopSbcGlUcnNS1gWtu9Q2jto2WvhgtB2roGwWyp7wsZudyHhqeLw=h305",
      "https://play-lh.googleusercontent.com/CxApBF84EDVWl6wUS1yeQcCdsOGaFgaI3lujcVqRuIUJiPcxGoPvy7br1D3f9XKW8VRT6hyHlZFFYR0ZbKSz4A=h305",
      "https://play-lh.googleusercontent.com/Jr_DSebXQK02c2iHuZ5thdxg5v3UsOY2wfE7LpaAuhpZxi-ZQeJfILU21zJODaZOg05ZqyzQ2m05nG42ald3=h305",
      "https://play-lh.googleusercontent.com/zYyKKicgmcvhFArPvVoqjUogVev1xsRkX8sa3HGuFJmJ-XiDljYfvinWCK6gzEXcYXruCIb-wbaxeWJnvM1_PA=h305"
    ],
    security: {
      checksum: "SHA-256: d241e4d372fc5927ad81d3542a4192dd",
      secureToken: "Direct clean download free of ads",
      cloudStorage: "Fast file storage"
    },
    tags: ["MOD", "Ad-Free", "Free"],
    isRecommendation: false,
    isRecent: false
  },
  {
    id: "7",
    name: "Netflix Premium App",
    slug: "netflix-premium",
    developer: "Netflix Inc.",
    rating: "4.5",
    downloads: "100M",
    size: "10 MB",
    version: "10.6.2",
    category: "Movie", // Mapped from "Movie" to match a base category or custom configuration
    type: "App",
    updatedAt: "04/07/2026",
    icon: "https://apkgstore.co/wp-content/uploads/2026/06/netflix-icon-09428465.png",
    description: "Watch exclusive movies and TV shows in 4K HDR resolution without paying a monthly subscription.",
    longDescription: "Netflix Premium MOD offers you unlimited access to the entire original Netflix catalog, trending world TV series, award-winning documentaries, and stunning cinematic feature films. The best part is that it does not require registering a credit card or paying monthly fees. Stream simultaneously on up to 4 devices in UHD 4K resolution and Dolby Atmos surround sound. Includes multi-language options with perfect subtitles.",
    downloadUrl: "https://www.mediafire.com/file/vy6k7lh1xtp022k/Netflix-v9.47.0+build+2-MOD-OTR-(APPS2APP.com).apk/file?dkey=vin2svoxm82&r=606",
    videoUrls: ["https://www.youtube.com/watch?v=GV3HUDMQ-F8",
                "https://youtu.be/L5AM7I2JgDM?si=IduY4U-CgoN5BAZr"
    ],// Perfectly fixed syntax error and successfully loaded multiple video URLs
    screenshots: [
      "https://play-lh.googleusercontent.com/bJrIdbqnzVixnnsYe8MgD2Ifsj95Az71ZBVyfHn34mLutfkWFvZG6W6Y6UAVQFBB6pnBFeX3NunRb23DqW-V6w",
      "https://play-lh.googleusercontent.com/QWBsHU-ACYxbmx-JsQd1UKL3QYiIe1nVqi4WnrC6D7FvRdIjo4RCrA3sS9gvTF8LLdg5w5ScBx1gRCZVtMqEB98",
      "https://play-lh.googleusercontent.com/-JL_3aAY99L85bez_VDAd2Kj_vITNDjLP7tjQqhf8JEbW1N3ppKBDSak4RKtkcLLC9EEBPSq3kzK0R91pklypQ",
      "https://play-lh.googleusercontent.com/UBMcCQ95xZuppNDv4DHCai60jqzxHNpgPNDPlp7ZBT-T-RS6YRdmyAic6TxwYR9hP5atUv7U21MvsdBuHHB2wA",
      "https://play-lh.googleusercontent.com/cxnMndqnsbcFGfLDk0lgxWJFRbO95GMle7runCUqOK1tV4tyW2ZdYVhD6JfPfRtQicF1DWVyMsXr6fGNu_UmGg",
      "https://play-lh.googleusercontent.com/1a1yokGJqW3LaJEqu4ai-l4-zKz4Fy0KR8LhggJfy4Q4vDgtJ9VWjViVPBghorazrYiQgUgKmzEKYw88m7t7MQ",
      "https://play-lh.googleusercontent.com/fZHmTfieMrR8QpiqJyaUOQBjWEtWZ2jFEesdShn4gchWtpSIf6RtLGYD7Ct2sLp7_XP1Gfkh248pqF6fy-gDdwI",
      "https://play-lh.googleusercontent.com/DmM6jsNTdgqNoDC-npaxhkxY6VCS49Z5B-pacu0RP4mWxFlYOhs2w8ZxJhofG3UaYMcpVh6tB0by6YXRlD5gLQ",
      "https://play-lh.googleusercontent.com/mRlPKnD8yWWILvIKEpSnE28niTg3e2UGkoXmUTPIcwAVzKG3P8C0inohOpkbkvtAKB-THH4wae2DQh1Py1JVSQ"
    ],
    security: {
      checksum: "SHA-256: e810e4d372fc5927ad81d3542a419ab7",
      secureToken: "Paywall bypass Mod",
      cloudStorage: "Mirror stream servers"
    },
    tags: ["Paid Subscription Unlocked", "Free", "Ultra HD 4K"],
    isRecommendation: false,
    isRecent: false
  },
  {
    id: "8",
    name: "8 Ball Pool MOD",
    slug: "8-ball-pool",
    developer: "Miniclip",
    rating: "4.7",
    downloads: "500M",
    size: "115 MB",
    version: "5.14.2",
    category: "Sports",
    type: "Game",
    updatedAt: "01/07/2026",
    icon: "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/10/com.miniclip.eightballpool.jpg&width=160",
    description: "The number one multiplayer pool game with infinite guideline lines for perfect shots.",
    longDescription: "Play with friends and become a pool legend. Face competitors from all over the world in competitive 1v1 matches or participate in international tournaments to win exclusive trophies. This modified version provides the coveted long line guide that allows you to visualize the exact trajectory of the balls from start to finish, ensuring perfect bank shots and mastering the most difficult tables effortlessly.",
    downloadUrl: "https://dl.8bpoolproapk.com/8.Ball.Pool.MOD.APK.8bpoolproapk.com.apk",
    videoUrls: ["https://youtu.be/MarGQrmbPm0?si=AF8RDd7cXCeDf7XM"], // Converted to array support
    screenshots: [
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-09-at-5.21.54-AM-1.jpeg",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-09-at-5.21.54-AM.jpeg",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-09-at-5.21.53-AM-2.jpeg",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-09-at-5.21.53-AM-1.jpeg",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-09-at-5.21.53-AM.jpeg",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-09-at-5.21.52-AM-1.jpeg",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-09-at-5.21.55-AM.jpeg",
      "https://imgcdn.latestmodapks.com/api/resize?url=https://www.latestmodapks.com/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-09-at-5.21.54-AM-2.jpeg"
    ],
    security: {
      checksum: "SHA-256: 7810e4d372fc5927ad81d3542a419a42",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Miniclip servers"
    },
    tags: ["MOD", "Long Line", "Free"],
    isRecommendation: false,
    isRecent: false
  },
    {
    id: "9",
    name: "ibis Paint X MOD",
    slug: "ibis-paint-x",
    developer: "Imaanshu N",
    rating: "4.7",
    downloads: "500M",
    size: "55 MB",
    version: "5.14.2",
    category: "Arts",
    type: "App",
    updatedAt: "01/07/2026",
    icon: "https://an1.ca/wp-content/uploads/2026/07/ibis-paint-x-icon.webp",
    description: "The number one multiplayer pool game with infinite guideline lines for perfect shots.",
    longDescription: "Ibis Paint X MOD APK has earned its popularity by combining professional drawing features with an interface that remains approachable for artists of every experience level. Its extensive brush library, advanced layer support, precision editing tools, and creative effects provide everything needed to produce high-quality digital artwork. Whether you are drawing for fun, studying illustration, creating comics, or working on professional designs, the app delivers a reliable and enjoyable creative experience. For anyone passionate about digital art, Ibis Paint X continues to be one of the best drawing apps available on Android.",
    downloadUrl: "https://cdn903.onehost.io/2023/ibisPaint_X_14.0.9_1785402201_latestmodapks.com.apk",
    videoUrls: ["https://youtube.com/watch?v=WwAQ0KbSc2Y",
               "https://youtube.com/watch?v=jBxoqMWLcbc",
               "https://youtube.com/watch?v=FGWBNcUupUU"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/KjfgitN0PxaWIc9SR0y3cebP0Jd_e_G60uZE_NSXpqnrzWMfa5bTlExxaTV47B9nrWEYb1jpBQJObIfMcX-xRpQ=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/1ykLwPhWJP_1CRoEfeVsV7sRN6YQV28Vm0fUIT3FuWinAfiJJPZLtgmm3o3yGu00klbLoWUKL13BFTSKPAgBP00=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/kHNr82olZY2GTW7W6LV76rkU0edTfIovoErKaU4mk-cRdxchgtNbmtW57qdhOHwxXhALJSHJdsUZB15bS9CKmGI=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/ezqj65P6eqUeNPyokehwU471iuKUzErRr9hiIExQom5fRl4qgu2FFonvG2w25j2KxmvZxHHlIzJ27wQ3R4AUVpw=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/52oC3ZJvG6rubJ84QhDAkCfX3YUOEDj2KlkbyOuWOo3iXA6M5GkQdLfANrwGrnFis1z-9lTrxfzoV5TxCNKw2ZU=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/JZw2b4Ffi9fLGwCdvOyBRSh-oKLJhwNA6asjWG5ZmSxA17YmTubxkFQyoCRnWUncgpFqHX6axEVEeGDvx4VpKgE=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/5lAykUR6o2vYW6dExj1_MKJOLQ9lTIq3UH2BPr6WRt6M35N1YExMNS1kXOpChaVpTyvTw7DHulhh97_yyIPI=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/hlNbZMbLGwvwQVg2H-Nv0gjgSx1ggvPrXAm90HqXi1450fzyEklc3Xc33d1UrTbKcOnjyJ50VLn-_xiNcMeu=-rw"
    ],
    security: {
      checksum: "SHA-256: 7810e4d372fc5927ad81d3542a419a42",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Miniclip servers"
    },
    tags: ["MOD", "Long Line", "Free"],
    isRecommendation: false,
    isRecent: false
  },
    {
    id: "10",
    name: "Free Fire Max",
    slug: "free-fire-max",
    developer: "Garena International I",
    rating: "5.0",
    downloads: "500M",
    size: "498 MB",
    version: "1.130.1",
    category: "Action",
    type: "Game",
    updatedAt: "23/06/2026",
    icon: "https://image-winudf-com.cdn.ampproject.org/ii/AW/s/image.winudf.com/v2/image1/Y29tLmR0cy5mcmVlZmlyZW1heF9pY29uXzE3ODIyNzkwODlfMDY5/icon.png?w=184&amp;fakeurl=1",
    description: "The Free Fire MAX Asia Invitational 2026 Summer (FFMAI) was a major online esports tournament organized by Garena with a $50,000 prize pool. It ran from June 12 to June 21, 2026, featuring top regional teams from India, Thailand, Indonesia, Malaysia, and other parts of South and Southeast Asia.",
    downloadUrl: "https://d.cdnpure.com/b/XAPK/com.dts.freefiremax?versionCode=2019118334",
    videoUrls: ["https://youtu.be/cNwifYfyho8?si=hRYjQ44RMyjWo4Si",
               "https://youtu.be/8tsQYDKPEhA?si=Il9Vy8JXDXiN82jF",
               "https://youtu.be/-LvuwRq7DNw?si=ZjkwfCpLDtt5_GwZ"], // Converted to array support
    screenshots: [
      "https://downloadr2.apkmirror.com/wp-content/uploads/2025/07/01/Free-Fire-MAX-com.dts.freefiremax-300x188.jpg",
      "https://downloadr2.apkmirror.com/wp-content/uploads/2026/01/01/Free-Fire-MAX-com.dts.freefiremax-2-300x188.jpg",
      "https://downloadr2.apkmirror.com/wp-content/uploads/2026/06/01/Free-Fire-MAX-com.dts.freefiremax-3-300x188.jpg",
      "https://downloadr2.apkmirror.com/wp-content/uploads/2026/06/01/Free-Fire-MAX-com.dts.freefiremax-4-300x188.jpg",
      "https://downloadr2.apkmirror.com/wp-content/uploads/2025/07/01/Free-Fire-MAX-com.dts.freefiremax-5-300x188.jpg",
      "https://downloadr2.apkmirror.com/wp-content/uploads/2026/06/01/Free-Fire-MAX-com.dts.freefiremax-6-300x188.jpg",
      "https://downloadr2.apkmirror.com/wp-content/uploads/2025/08/01/Free-Fire-MAX-com.dts.freefiremax-7-300x188.jpg",
    ],
      security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "official Grand Finals broadcast:"
    },
    tags: ["MOD", "Long Line", "Free"],
    isRecommendation: false,
    isRecent: false
  },
    {
    id: "11",
    name: "Jio Hotstar",
    slug: "jio-hotstar",
    developer: "Imaanshu N",
    rating: "4.8",
    downloads: "177M",
    size: "89 MB",
    version: "26.04.15.1",
    category: "Tools",
    type: "App",
    updatedAt: "04/24/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/bp4jknyVZ8yDKhER9thIS1p9MBeU2LABqBX-sO8uaL1h5_keqlgMUmXv-CjfRWaqKw=s150-rw",
    description: "JioHotstar is an application that presents entertainment programs from the company Novi Digital. This is an extremely popular application in India and the US, you will easily find the content you like and have a variety of experiences. In addition, JioHotstar also supports many different languages for users to customize. Language will no longer be a barrier preventing you from accessing top entertainment movies and TV shows.",
    downloadUrl: "https://s1.1phut.io/v2/j4AY",
    videoUrls: ["https://youtube.com/watch?v=wELTVUjFbGY",
                "https://youtube.com/watch?v=01Ps5mDUkyo"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/jw9bHtu-k6ztqmZtud710UxehHrycUR9d8dHL3k2DNwcZJ1brxY2rv5EiX3jTCDwdJLAysDVMeVzTHkBiFMQH84=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/HqfBYKArJwswZvKDD7BSP0AZF74MUGKm0BGPE10juRqWhIkZTJ3eHv14NqinvngvIiccpZfoje0o2wnJB2yso2Y=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/mTlWjybBSxZly2jOjPvlUmTDJOJXFhFIdNuzhPMg-8sEXxJkSJKFZatEX9YWkTBPZXbE1dUrECLQ8aey3W7pkhg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/1STaFRX428oh3h7fTqSjsKddoH1UrHTdkdFDtAqrJoFKQkg58lt6KODom60E_5-Lp3y3YU4xBtymb2BrcqEQYg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/WSg9X5ZEiulI1X6ILtrRVuoEeIUd4YrmURuN_9WjrsEtuh8FmoJ6CwHd1DC2U8ApPTBS98LVDsEPzkT01sNvrWk=-rw",
    ],
      security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "When two worlds come together, the extraordinary takes shape."
    },
    tags: ["MOD", "Long Line", "Free"],
    isRecommendation: false,
    isRecent: true
  },
    {
    id: "12",
    name: "MovieBox",
    slug: "moviebox",
    developer: "Imaanshu N",
    rating: "4.7",
    downloads: "500M",
    size: "58 MB",
    version: "14.0.6",
    category: "movie",
    type: "App",
    updatedAt: "01/07/2026",
    icon: "https://apps2app.com/wp-content/uploads/2026/03/moviebox-150x150.webp",
    description: "The number one Free, HD, No Ads. Watch HD, Offline. No Ads, Free HD. ​Premium, Ad-free. ​Fast, HD Streaming.",
    longDescription: "MovieBox Mod APK Key Features:Unlimited access to premium content, free subscription model, massive library of movies and TV shows, extensive collection of web series, diverse genre support including action and drama, horror and romance categories, offline content downloading capabilities, uninterrupted offline viewing, high-definition streaming support, 1080p video resolution, 4K playback quality, optimized streaming performance, multilingual content library, native Hindi language support, English language accessibility, broad regional language options, no mandatory registration required, privacy-focused data handling, completely ad-free interface, seamless playback experience, intuitive user-friendly design, efficient navigation system, broad Android 5.0 compatibility, high device performance optimization, frequent library content updates, instant access to new releases, accelerated loading speeds, integrated data-saving modes, advanced security protocols, clean minimalist user interface, unrestricted content exploration, personalized favorites list, customizable playback settings, advanced internal media player, enhanced buffering optimization, streamlined installation process, stable performance on low-end devices, modern aesthetic interface, instant content accessibility.",
    downloadUrl: "https://files.modapkdl.com/ROOT/All%20Documents%20File/Folder%202/MovieBox_v3.0.16.0709.03_(50020116)_Mod-APPS2APP.COM.apk",
    videoUrls: ["https://youtu.be/rWoUM_nMPtc?si=bC-_r2uBqnE9f83m", "https://youtu.be/c8kXsCAOj8Y?si=TQhywvjtO0O0g16I"], // Converted to array support
    screenshots: [
      "https://play-lh.googleusercontent.com/lTQL8FNUICbVoVuSO8jMSRNIsz1vJs0ggttRk6d4TTsMiirAeN9c06oH6h-W6PNYUE=h305",
      "https://play-lh.googleusercontent.com/tkBwbyjRS1Wxnjrs_D55htQWuByuK8eHBm1pPb1so0_kv204P9pnqKF7097yLoySzQ=h305",
      "https://play-lh.googleusercontent.com/x-hk0oonVM-SLHcvbJMpYMz7KHflTUtJuqCcecKyke9saZDj7AA4WNZUu_kGA2TikSzd=h305",
      "https://play-lh.googleusercontent.com/yB9xDtcmAHScwfq2PDKcik1ASCnukkJMXWuRop21htGi5aDwxoctsqyo92tx3HJNhsI=h305",
      "https://play-lh.googleusercontent.com/VkcwvhZ6JJ38NA7t-EiNc5KT9bEOABWhM2BYmgwYGGGzTdH3lz_h4eDqgpnGardsBU8=h305",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Moviebox servers"
    },
    tags: ["MOD", "Long Line", "Free"],
    isRecommendation: false,
    isRecent: true
  },
    {
    id: "13",
    name: "Sally Face",
    slug: "sally-face",
    developer: "Imaanshu N",
    rating: "6.0",
    downloads: "1k",
    size: "732.86 MB",
    version: "1.5.51",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://apkvision.org/wp-content/uploads/2026/08/sally-face-140x140.png",
    description: "Sally Face invites players into a haunting adventure centered on a boy with a prosthetic face who communicates with the dead through his handheld video game system. As he and his friends investigate a series of mysterious murders, they uncover dark secrets lurking in their small town. With a unique blend of 1990s cartoon inspiration and personal nightmares, players can engage with bizarre characters and tackle challenging optional puzzles that deepen the narrative. The game features handcrafted art, design, and music by a solo developer, creating an immersive and unsettling experience.",
    downloadUrl: "https://dl.apkvision.org/sally-face/Sally-Face-v1.5.51-full-apkvision.apk",
    videoUrls: ["https://youtu.be/ZUvCKwkbl3c?si=RGqEMgnLAgljYz4Y"], // Converted to array support
    screenshots: [
      "https://img.apkvision.org/sally-face/sally-face-1.webp",
      "https://img.apkvision.org/sally-face/sally-face-2.webp",
      "https://img.apkvision.org/sally-face/sally-face-3.webp",
      "https://img.apkvision.org/sally-face/sally-face-4.webp",
      "https://img.apkvision.org/sally-face/sally-face-5.webp",
      "https://play-lh.googleusercontent.com/BK987Mgsgv7o9sIxOH_416_cawtBqZwPuGgYrHoqsiahEj_Rge5e76qbi5fQd4GL7vPlj87pgi6u9TsxD4q_GWc=w1052-h592",
      "https://play-lh.googleusercontent.com/RbWQeaOd82Jljkc-TMl6w-hCHpGpzcoiL9qpZNx6UTA6yX1XOLGhO58C6CxB743OGGKjrnAQ5Fkc_lWLgZs=w1052-h592",
      "https://play-lh.googleusercontent.com/vO96TGIFLwyjEtNP1sBdLCALj004ndoiteRrjh68IbrwbiBIeAGHHqM8SYwwR4t8euHtCXuvGo2Q7Ic9rAlV_Q=w1052-h592"
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Moviebox servers"
    },
    tags: ["MOD", "Long Line", "Free"],
    isRecommendation: false,
    isRecent: true
  },
      {
    id: "14",
    name: "Caravan SandWitch",
    slug: "caravan-sandWitch",
    developer: "Imaanshu N",
    rating: "3.4",
    downloads: "5k",
    size: "886 MB",
    version: "1.4.196",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/w1OHWOIIh2j98zzTn0fVs1DTCeASlzAyzgBAlfPTGDFwh0tzveHbB3KLvyWfHVrr3Uz55miJD3VYL8Q6c0AU=s150-rw",
   description: " Caravan SandWitch is an open-world sci-fi adventure game that takes players to a deserted planet filled with vast landscapes, mysterious ruins, and a heartfelt story about searching for a missing sister. Instead of focusing on constant combat, this open-world adventure game offers a relaxing exploration experience where you drive across deserts, uncover clues, and meet unique communities surviving on the planet.",
    downloadUrl: "https://s1.1phut.io/v2/5ym8",
    videoUrls: ["https://youtube.com/watch?v=Z9IHy90XgNo",
                "https://youtube.com/watch?v=b4_HKS5q4MM"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/qvL37EvRjZK8qXfpMq08fIYXNJHwVoXZmyOJw65eDcLvN0HXxJi4QUcSqvWzYGRyP5fykRIzzn0842JCNpZF=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/Rbs4Xd6hURoOz5ePMvfsIf0E2DwWznIvtI5cIw2d1MGtslYJnTDrzRKAZPs4pu87o9EfZyOgCqzxfz0HV-dW=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/iXf_jIcScc3m2E4iH_exuaBcjlwaeUEGJyX35cQVf_IiLJt6oWWTqcAcwsGY5RnoMzpyIa69n-FrYsa_xYja=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/D3ijmXob7Nh9HCs6Q-5mAN92kyjS0EKeN3xTTzxHFubPKula8tY5BpfjFaFMnrQAxwy-oVY5ASRjNi0h0UgK=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/zoBF24RMUwi6Ja_i0VIcu-CjLvPsQG63_FizIXtPA2QFs145yHpCYWD2awojyE-c6CtlieY1KsPq9AravH6Fbg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/gwNhePNMNLyTOzURLwPYUsONrAViJCccBmdAcOx32rXivzK8d8j62m8ttTSzDNfE_FkC9wI5-frD4v0eKUsSWLw=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Moviebox servers"
    },
    tags: ["MOD", "Long Line", "Free"],
    isRecommendation: false,
    isRecent: true
  },
    {
    id: "15",
    name: "Little Nightmares",
    slug: "little-nightmares",
    developer: "Imaanshu N",
    rating: "5.0",
    downloads: "15k",
    size: "1.2 GB",
    version: "1.4",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/vEJAwZwhOv7Wzf1Md7PsMzOyo087y0Z4rhRgidtfv03c682RicoBz3BOsrigdiXA-7I=s150-rw",
   description: "Little Nightmares has a part 2 on PC and console, but for mobile we have only enjoyed Very Little Nightmare, the mobile version of the original game that didn’t have everything as expected. Now everything is different. Puzzle enthusiasts, listening to Little Nightmares for a long time can officially play this game on mobile in its entirety. You can experience the full story, content and features. The graphics are as good as the console version.",
    downloadUrl: "https://s1.1phut.io/v2/4pKa",
    videoUrls: ["https://youtube.com/watch?v=aOadxZBsPiA"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/HeyCMUVHE3-YbyNmypziTF3yDI9edQKZYAzVdL7slCwrqEBwzAWOJBVXkaQKA63dCQ=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/bYN-PFWw1oO6YaYJHu64ZpSlImVfIp6vxRxpc20XBKRU2pCbISNiNTDSzqTnuqMo-54=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/nLDF-IZZlTgIvL-NNVKdI8Bdz9HK2MErU5qg8W-3Q7HDJiVRIM9UUdqR7vrQMNBZWg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/FfYV5lsivGjYZ2G91lGkRAniQU8TKZCjoT9fQsVnI1U5W4U8n5I7On-BcTeWSa8YSog=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/Ctsqn7NOFx1NIhz8MqdE_xBLZgeK6HaL1kCu6XKZ8xri0BgfnrgUwYDPsaFtoBsVYxvZ=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/lvpxljRwoZPWWycoZWrujkveO8nd-TFFtoGrstdYX3Jkx8mw7uvAGWp2NvmWD00ikA=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/NvpJKUbb4RFJKh3BUqUOh5DUHVI6vCoTZVwFuj_h2njPBqMOiJ9gpeyNxpATnm44zbI=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Takano3D servers MOD APK"
    },
    tags: ["MOD", "Long Line", "Free"],
    isRecommendation: false,
    isRecent: true
  },
    {
    id: "16",
    name: "Final Fantasy VII ",
    slug: "final-fantasy-vii",
    developer: "Imaanshu N",
    rating: "3.3",
    downloads: "500K",
    size: "2.0 GB",
    version: "1.1.0",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://share.google/ssu6T0LXChNXsjbK9",
   description: "FINAL FANTASY VII brings the iconic RPG experience to Android, featuring a captivating story where Cloud Strife joins a rebel group to challenge the power of the Shinra Electric Power Company. This port retains the original’s dramatic narrative and introduces 3D backgrounds and full combat stages. Players can customize characters using a versatile material system and enjoy new features like enemy encounter toggles and a Max Stats command. Note that the app requires significant memory, and users should frequently save their progress to avoid bugs related to transportation mechanics. Check device compatibility for optimal gameplay.",
    downloadUrl: "https://dl.apkvision.org/final-fantasy-vii/FinalFantasy7-v1.1.0-full-apkvision.apk",
    videoUrls: ["https://youtu.be/p-pgBQgFLP4?si=Qu4sAMceSaO2jmlt"], // Converted to array support
    screenshots: [
      "https://img.apkvision.org/final-fantasy-vii/final-fantasy-vii-1.webp",
      "https://img.apkvision.org/final-fantasy-vii/final-fantasy-vii-2.webp",
      "https://img.apkvision.org/final-fantasy-vii/final-fantasy-vii-3.webp",
      "https://img.apkvision.org/final-fantasy-vii/final-fantasy-vii-4.webp",
      "https://img.apkvision.org/final-fantasy-vii/final-fantasy-vii-5.webp",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Takano3D Server on MOD APK"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: true
  },
  
   {
    id: "17",
    name: "FINAL FANTASY VII EVER CRISIS",
    slug: "final-fantasy-vii-ever-crisis",
    developer: "Square Enix",
    rating: "3.8",
    downloads: "2k",
    size: "394 MB",
    version: "3.6.0",
    category: "Tools",
    type: "Game",
    updatedAt: "04/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/s_JGrjTxF2GHVrlp8U0iwxE4UfLq6CHclZheCZuEp4m1suyE4w2CfUA-DVXk8mDyI23gM6pINJ0p2nWyT1A8NLI=s150-rw",
    description: "Developed by Square Enix, FINAL FANTASY VII EVER CRISIS, a customized mobile version that will help you relive memorable moments, iconic characters from the world of FFVII. It’s time for you to experience this great heroic journey right on your mobile.",
    downloadUrl: "https://s1.1phut.io/v2/xmM3",
    videoUrls: ["https://youtube.com/watch?v=87TNASkXOWQ"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/tZn49K2htCKaHZH8Pz3KWOZEeCWbYfk2Z5NZVsYlP0YfIOJCVAtR6YQ5CudI2TAKgNkdNF-H9rnO2_6fO5yP=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/bgWy0vOrdFCxQP5tfvY1hT0WctDhHISfnoMc6HT1ngGiJXdpoeRPZWZbgrGe6gF_V1s=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/U021ufSiXXN0UWmT1RCmz9OyK1E5syRO5y9r48D1Is1q08F8LFZxbGb4gRl71suZFuEE=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/KusXwq3H_U1PucnD6TVjAzdi7GSV5A8CyFTdb9oJ6wAIzzgCbROLz7DsM3Vyra89XAyk=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/0pkVAJMpIk823l4gkw7p-YZADempMJSgAu_B-UF3FjudnrDABOdeR_SNUXTNWNpqrg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/yj1VLQLh0DlLvrhJmdkk2sKHlniSUyX6TOMkNAjjUEb7MblNqibYOeJ2vw71tve0Zw=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/DcLPhwjso1iv1p0y6pE6yxG5vgqrT3TXqdcZecXCR9RbEjQb1Zc3pWfbl_6ctiwbeiw=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Takano3D Server on MOD APK"
    },
    tags: ["MOD", "Free"],
    isRecommendation: true,
    isRecent: true
  },
  
     {
    id: "18",
    name: "Webbly Life",
    slug: "webbly-life",
    developer: "Curve Games",
    rating: "4.5",
    downloads: "5k",
    size: "1.41 GB",
    version: "1.0.0.3",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://play-lh.googleusercontent.com/cH7yJARfE_wJ2lXnrsKiXnpAdJlv5VNKWthRQdQ4bnOnYYZJjmuoX7inCu7MKGU6r2unnNG6VIIe0z9EXE_3=w480-h960",
   description: "Wobbly Life invites players into a vibrant, physics-based open-world where exploration and fun await. Tasked by Grandma to get a job, players can choose from over 20 unique roles to earn money, unlocking new content and customizing their characters, homes, and vehicles. With a vast landscape filled with towns, mountains, and hidden secrets, players can embark on exciting missions, collect pets, and engage in mini-games. Compete with friends and others globally to climb leaderboards, making every adventure a chance for creativity and excitement in this family-friendly sandbox experience.",
    downloadUrl: "https://dl.apkvision.org/wobbly-life/Wobbly-Life-v1.1.0.7-full-apkvision.apk",
    videoUrls: ["https://youtu.be/uALEoh3aj3s?si=L9OockkFhNVrkU_P"], // Converted to array support
    screenshots: [
      "https://play-lh.googleusercontent.com/9yImHsrLfjLmM0sYvwUoCUY_oNqALzqdRWwwhd5e1A4cqJcD-iiOrt0jm-RdPWWjAOzLhIZU9l-tZyuPMYP-zic=w1052-h592",
      "https://play-lh.googleusercontent.com/2hKIwF61Xsx_wLhHFrn9quZbH_CuiNEZUEw96TJ-Ufw0tapIa53CU7hPULbjT8t8c15gWDG9vKJR4TuOXCH7PA=w1052-h592",
      "https://play-lh.googleusercontent.com/Gbnw-wBXYFtZvDboDJ9T7quILXGBVrKLy6yC4FOJa-ypvWAQCgFWIfswbUkpoyFwOpynUOgj8RnAoEsbzuTijg=w1052-h592",
      "https://play-lh.googleusercontent.com/drTB9Aeb7oQIRF0hrKEB5SSAe_Zq6VHGoaA8P5vZegz81Qd9uaArSNrIpWSFWuoDoBMNbNdg0WTJUxPQi3TqTA=w1052-h592",
      "https://play-lh.googleusercontent.com/N_GnOEJrE3UWmIpG8CtMHrwJ7yeF9cCYsuscwkcQ4DHberHyMoJ6TxKL1Wzl01dykGwna9oGpjM9JnR16kxq7A=w1052-h592",
      "https://play-lh.googleusercontent.com/ye6JelEa7ZE4nkqUdDD860_pTkyEBnmn4ndfDP63CyhjY6V6wN5TrlDEzEjGs0MJxvX67uRYA6BjFtfC-16T=w1052-h592",
      "https://play-lh.googleusercontent.com/IMAUt2XDGHoZNvp_HFmSHG6j8qvXCbsy47iyOuMr6-V0BWHJjhtm9nLCb2plNIr2uRbunKl7jdmWbT1JXBg3=w1052-h592",
      "https://play-lh.googleusercontent.com/3edzzyf2yto5Jj2jCrEKHvZ3b74Uu3AS2CGNGs0b56S4fd53vw5R5fF3kQ8L9F74WlZhFrYXboTPhqslIUHv=w1052-h592",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Takano3D Server on MOD APK"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: true
  },
      {
    id: "19",
    name: "DREDGE",
    slug: "dredge",
    developer: "Black Salt Games",
    rating: "5.0",
    downloads: "1L",
    size: "653 MB",
    version: "4.5",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://share.google/Hei727ckNLBMaYEww",
   description: "DREDGE is a captivating fishing adventure game that combines exploration and resource management. Players navigate through mysterious waters, uncovering hidden secrets and completing quests while balancing the demands of fishing and survival. As they catch various fish, players must also contend with eerie elements that lurk beneath the surface, adding layers of suspense and intrigue. The game encourages players to delve deep into its rich narrative and atmospheric world, blending a sense of adventure with strategic gameplay.",
    downloadUrl: "https://dl.apkvision.org/dredge/DREDGE-v1.5.18-b100518171-unlocked-apkvision.apk",
    videoUrls: ["https://youtu.be/sJX9VSp2vAA?si=JboP9PsAyuj8TVb7"], // Converted to array support
    screenshots: [
      "https://share.google/ew3gbGOnlM2xGk3xD",
      "https://share.google/3VCnOx4n8bg7RJGUa",
      "https://share.google/At4vPSUMIwrjmObjh",
      "https://share.google/bWMPjuMNUf87rNnhB",
      "https://share.google/3O9sgV4dyIKGqQ4hG",
      "https://share.google/1r5lvYirxQipIQqzP",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Takano3D Server on MOD APK"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: true
  },
     {
    id: "20",
    name: "Minecraft",
    slug: "minecraft",
    developer: "Imaanshu N",
    rating: "4.9",
    downloads: "200k",
    size: "1.0 GB",
    version: "1.26.44.3",
    category: "Adventure",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/27O5tpaYE82W6m30rJ_MX3-UvshlDM6O8oXDxb6GseYW2T7P8UNT19727MGmz-0q3w=s150-rw",
   description: "Minecraft is not just a game but also a rich and limitless open world. With a version specifically designed for mobile operating systems, Minecraft has unveiled a unique experience, allowing players to immerse themselves in an infinite world of creativity and exploration on their Android smartphones or tablets.",
    downloadUrl: "https://s1.1phut.io/v2/4DeD",
    videoUrls: ["https://youtu.be/BLtLrFNRE-E?si=dCx4oPY0qkUj_7q-"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/E3ae4Jm7cLqmGEHg4In5rXdKrMAwDPPNb26coEAESZw4RjvkgS_bBJtRwFNGZrBMfw=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/ZSMzOOE-yQt2I2VjA1rqZ2hkQ1PzWBDXUnqkW6sCQMGs2d_H6X2UBVB-LF-B6Gm4VjYz=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/Va5XplRkZCroi-q8NZI5TLd1vHHndW1ps6o98X4fvtnSMwmS4iOHxwxB2B7fri-lOGA=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/V1CnCHYr1JP9pYrJLs53qS3YG9rbJVhxmLApqXY_pWt17ZQIwbXIibXeC2gGeckksy8=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/nZTKxyLI6340xoPhTTLMODDCCb9GW5tdb-_7rcOsN350fnGd7c2ph7-0RgC8Ot_-E4s=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/srkig0NrEF-DQI067-yYDRWmtDGyMWet_ocNu7GBU0fnoElm6WVmCXBgMZYJ8H4kfQ=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/zsJ6j0KZTru9deKTA4cI2NXzsFNgD-Qd-fl3B4TVItRlVSwVibo7q8gNcFysvx51sso=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/dqCRCJb1nRGv5XtuA2Ml4mTDYuGRaD68juil4wfFHsYWiV0kvjG1mgDpiZHTMWG0-WD1=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Takano3D Server on MOD APK"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: true
  },
  
   {
    id: "21",
    name: "Minecraft Beta",
    slug: "minecraft-beta",
    developer: "Imaanshu N",
    rating: "4.9",
    downloads: "200k",
    size: "1.0 GB",
    version: "1.26.50.27",
    category: "Adventure",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/27O5tpaYE82W6m30rJ_MX3-UvshlDM6O8oXDxb6GseYW2T7P8UNT19727MGmz-0q3w=s150-rw",
   description: "Minecraft is not just a game but also a rich and limitless open world. With a version specifically designed for mobile operating systems, Minecraft has unveiled a unique experience, allowing players to immerse themselves in an infinite world of creativity and exploration on their Android smartphones or tablets.",
    downloadUrl: "https://s1.1phut.io/v2/2oa7",
    videoUrls: ["https://youtu.be/BLtLrFNRE-E?si=dCx4oPY0qkUj_7q-"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/E3ae4Jm7cLqmGEHg4In5rXdKrMAwDPPNb26coEAESZw4RjvkgS_bBJtRwFNGZrBMfw=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/ZSMzOOE-yQt2I2VjA1rqZ2hkQ1PzWBDXUnqkW6sCQMGs2d_H6X2UBVB-LF-B6Gm4VjYz=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/Va5XplRkZCroi-q8NZI5TLd1vHHndW1ps6o98X4fvtnSMwmS4iOHxwxB2B7fri-lOGA=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/V1CnCHYr1JP9pYrJLs53qS3YG9rbJVhxmLApqXY_pWt17ZQIwbXIibXeC2gGeckksy8=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/nZTKxyLI6340xoPhTTLMODDCCb9GW5tdb-_7rcOsN350fnGd7c2ph7-0RgC8Ot_-E4s=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/srkig0NrEF-DQI067-yYDRWmtDGyMWet_ocNu7GBU0fnoElm6WVmCXBgMZYJ8H4kfQ=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/zsJ6j0KZTru9deKTA4cI2NXzsFNgD-Qd-fl3B4TVItRlVSwVibo7q8gNcFysvx51sso=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/dqCRCJb1nRGv5XtuA2Ml4mTDYuGRaD68juil4wfFHsYWiV0kvjG1mgDpiZHTMWG0-WD1=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Takano3D Server on MOD APK"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: true
  },
  
   {
     id: "22",
    name: "Eyes: Scary Thriller – Horror",
    slug: "eyes-Sscary-thriller-horror",
    developer: "Imaanshu N",
    rating: "4.9",
    downloads: "20k",
    size: "1.0 GB",
    version: "8.0.88",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/E1YAxY5YgAqI9kR5MAo8lzsfaSbgsS0tevynKQIaVxbCOKLeYi6d8NYaLQRlsGpAzfcU6Kgt1H2ntiY89Aow=s150-rw",
   description: "Eyes: Scary Thriller – Horror is a terrifying survival horror game that combines exploration, suspense, and supernatural encounters. The game places players in dark and mysterious locations where they must search for valuable items, uncover secrets, and find a way to escape while being hunted by frightening creatures. With its unsettling atmosphere and unpredictable threats, this horror survival game is designed for players who enjoy intense and nerve-racking experiences.",
    downloadUrl: "https://s1.1phut.io/v2/vlrB",
    videoUrls: ["https://youtube.com/watch?v=_a5EbWkfwyc",
                "https://youtube.com/watch?v=n4dbmcxUM_I"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/aSGnh3x2ovfNhavd6TFquXsSK2yXRa61_02tNi9zJDgWQxDAZBtjYFCaVCrH86NSRKeSERxFR5lqUClC6XhW=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/WhjYoeQnM_ilzplnOI0ThF18YjvYUakz-LjonjA79m4ywstFsAsYAhJToz7oqR8swR9JMTRY0cqJYU9K1ky2=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/abvLUJXSjHAAFXRZ5b6_cATPNXApDyHQtygK8Vh_j2-EwCCDnI1nvs0XoFdq0pFXkA_7Cqw9EfxA8ULHBPd4zA=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/lyseNtJQOFol5ZALiWx4Dy34Ej25pU1HK0xEalzzdkqlDGBr9JYdYLOaIbhk9-INnqevquC7mV5aOmtdNfNZLZ8=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/fo5pZ9-vZjxkbZoUaa8MLibjjlxyZcta9su512JCcI7re25gAdPbaV5enoVhyXuHgGBMwIVfdh_CZgOTv_C1YQ=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/M8T4NCjwOGlhwVzqgHtxMX90gw0wvL3nK8e_vSykgUMFZOTXfUi-lsR44PjBKF0o1eyXQQzsZqNiyxSbtNvMFQ=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/jKmXdToU6yV7hazSTqBZxUgXbkCT3m6PoWgPgi4pRuKv0-19vVOEPRnGeUF7zjXARjQzaGMvsW4eZlUWJIt_gA=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Takano3D Server on MOD APK"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: false
  },
  
    {
    id: "23",
    name: "Machinarium",
    slug: "machinarium",
    developer: "Imaanshu N",
    rating: "5.0",
    downloads: "33k",
    size: "301 MB",
    version: "3.5.0",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/8s7VpaT4BJgaTq8u7eF2FIgW3-gOZzdOYRvI6-edXj2mpJms_XZS8ULxbe1VSd8RoVs=s150-rw",
   description: "Machinarium is a fun and beautiful point-and-click adventure game for Android mobiles. Although it was released a decade ago, until now, Machinarium has received many compliments for its beautiful graphics, vivid sound and extremely innovative gameplay.",
    downloadUrl: "https://s1.1phut.io/v2/ezLZ",
    videoUrls: ["https://youtube.com/watch?v=uwZBdWRSBRs",
    "https://youtube.com/watch?v=4xb3IImki-4"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/UnB9YP-Gt0FpKHDtv6KmqMJhPuxTCOUTrcFqUUVGmYf56_eAhqWC6wzF2seTEXAh2g=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/ZJzdfmw2oTY3MoV6wxJlk63rAl7hLj60MuVvRC-0vvb7TY4o5ixjmWMUWtAtAryFc2c=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/NJ4zNH6axXLxGn_bn5jTwj_YeozXZvV1bSql85M3Y2Xhj36zDBfKc4o9BMpCecOJgsg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/GBoDpK1JO91ZGqjUypZ-O8mKCyI2mnDOsDOH6RDCXDuqNE1Qh5MLTWuZbetyvITN1Xs=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/e0KDKNCSahPDeffA1hVQr-o9eMJQ8ipcp97vaOtFaUCjM9HJauNvQhqqxgGaXOalEr0=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/ljTzIpQcsTo1EO37EFlszOiTNc4bAU6iN2_U_vv6v_O3kUhn-rb_AODQiNsHQTaTTv3K=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/yG3szf-3TV-YioVtJ0j31qkdcCG8dUz2WmlZb2cx40UchTDVxbSsC0FhvH91ECcXMQI=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Moviebox servers"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: true
  },
    {
    id: "24",
    name: "Dream Road: Online",
    slug: "dream-road-online",
    developer: "Imaanshu N",
    rating: "4.3",
    downloads: "100k",
    size: "623 MB",
    version: "1.4.3",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/Zwg0qf7UFn4JYuf-ftl2_fty827AI08IAsbhTl-hJ0cJUSxn0L76e6O5CU5R7fdgSw=s150-rw",
   description: "If you are a street racing enthusiast, or love the excitement of chasing opponents on supercars, Dream Road: Online MOD APK is exactly the game for you. Exciting adventures around the city on your dream car, are you ready to conquer the challenges in this game? Let’s explore right away.",
    downloadUrl: "https://s1.1phut.io/v2/5yNp",
    videoUrls: ["https://youtube.com/watch?v=Xv69QyU3c6w",
    "https://youtube.com/watch?v=Fv7GmYMyC0o"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/q_7IYmzs0D6vNw1mEsz7BpwsQl4MC8RTAtV6aS0LPM9jKCCDWm86pFe7_Dcz1NwE7OI=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/bTp5-ePcKm4VhmX-v5MJldF8Rnmkd8aMCltQptuW5_TYfSdG6vWdtZusa12xXPdFmk4=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/SKLDBTp4a03-G2TsiITU3gBA3CVlGLuwX8vtiViU2akmJ8vOyVGU6yQ-KmVUv7HgUJI=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/DYe5durDQ2JTisaC_ib4HIxfsVdZrzfYLDJIRaWIRMg7ceNC_mT8-b9BcWsn5nyS2g=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/s6dyNtSJtqiC7Jb8Z-RuT37DRvme6ZyL7K7OaynAdOFp-z6Vikk4RzMhq9rX3LOd0Ew=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/EeoFP4lI-6jkI9TcOXCFKQyn0XSt5-i3DpJYgNuzbgQUOU_zk5yXDRoxVdaaYWZc1IVu=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/1tN2LWB6dXxgxH81Ow-t_G_0PQYIlhfY4oQmLSHJmjGKgQXkMj3T582FpNj1HDfY30k=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/i_pQh1uuFlDMnucJf_1xWjuAhlDVRIN5UN_Al4lfKkxwpz1VahVRKkSmAcbQIqjqHDU=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Takano3D servers"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: true
  },
    {
    id: "25",
    name: "Anime Depth Wallpapers",
    slug: "anime-depth-wallpapers",
    developer: "Imaanshu N",
    rating: "3.3",
    downloads: "10k",
    size: "30 MB",
    version: "1.1.2",
    category: "Tools",
    type: "App",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/jYmevEkyKdHZs_FSQEIRg8Ifxx4YU2-BQtso3Z0iQkMPM9w9ZkrOcbD7rys6Kq34t4Evufy1UVOgwwP0y4KKWc8=s150-rw",
   description: "Anime Depth Wallpapers is a wallpaper application designed for anime fans who want to give their smartphone screen a fresh and distinctive appearance. The app focuses on wallpapers with depth effects, making images appear more dynamic compared with standard static backgrounds. With a straightforward presentation, users can explore different designs and select images that match their personal style.",
    downloadUrl: "https://s1.1phut.io/v2/KXla",
    videoUrls: ["https://youtube.com/watch?v=4DmFW9UMAzc"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/JmG9-c02qUgUmdF01q5FLOIkIDGsPuwkY8n7T8FaYvGZ3D6mw_dTTyYfoK5sWAYogRBLVDVfZT7jqt3b0oHRUA8=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/TGUPr427Ds3OGCoX3YKl0oNlH4yiSuU1CEpV-Z4NG99B4RGpCH1epLAoqRddReiwUj3prIcuB7o7DFmvP-Hrww=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/Q-42XySZw216oMTBjfiFKPWxkG0itXxOty0WgywryqopIx-BsKwhY0yV6D0kC4tREguQ-90OFZSE1FBt2Lhq8Q=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/Q-42XySZw216oMTBjfiFKPWxkG0itXxOty0WgywryqopIx-BsKwhY0yV6D0kC4tREguQ-90OFZSE1FBt2Lhq8Q=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/TiI36KbqM40dposlY62or87M3vz4-0qYldR69F2K6Xbmztly1f6mN0lezurcFhK5KVTp1pCm3EOFUgCgxEBJ6CE=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/A7MB3x2fNC5RBE1of3uU9wKls5LKzEKtYeByVDrqOB9ms0cJ-MQj3--s2J8yO4zYQlt_oEzo61yYTOXBWwF9dg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/ieAlnx4Wlx_FrWHD95kD4nmotH2gWBWrcDtHWRMFf4Y-R5bVnyIWH1rLvfxakCTG3NH-yZzgmPpAPP2WaOYSvA=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/_TTRaQUR7ackumyW99uAZHTn0kxhryD-zKvNhwPtQgfrfEtySIGOeRUjwsPaKZzAMt6oo3e5LFV8N0NHF-My=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/o0DMdFJPdzJu10exK1zfiyahr4_Bt8c1kqzDo6nrHhLVW-1UP9wKL78X-FoJ9Erq2EVvUbCakNvtpEpP0bx9=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Takano3D servers"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: true
    },
      {
    id: "26",
    name: "TrueCaller",
    slug: "truecaller",
    developer: "Imaanshu N",
    rating: "5.0",
    downloads: "100M",
    size: "96 MB",
    version: "26.30.5",
    category: "Tools",
    type: "App",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/qtgLcbI3f7CHcg8vUjYQQv3jzJ05-prQ5wr6VN0F-ehAFqLEjNNhFD_QbjujOAy-r4w=s150-rw",
   description: "Life is increasingly developing and becoming more complicated, so the leakage of information as well as personal phone numbers on the Internet is inevitable. There are many ways to infiltrate personal information, one of which is through spam calls and messages. Therefore, understanding the common psychology of everyone, Truecaller was launched to support users to limit the above situation. So let’s learn about the Truecaller application to know more about the features and benefits users receive when using it.",
    downloadUrl: "https://s1.1phut.io/v2/vbBB",
    videoUrls: ["https://youtube.com/watch?v=j4gGqUVBFsU",
    "https://youtube.com/watch?v=7949Q9PM528"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/9ClODl-X8Q0knZWaCbkNTgl3HU_PR0brO8-HEdDpgizF7Lh9XtrI3qPuE7jRB8_qZnpwu7ALkItbtFcbOY6hBR4=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/1EOKR5B-LYsbSkoFsYOedir7v1WGYOyKk6_FGEUeW3Zk-8wssWWvuE-cdUqVjGsAkV09KQ9L9LjzltLz9M6BQrU=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/XjFnPExxAVVNmwkrECdRoiINaa85eQiFHxpj2077Qugv4LBVIA_Of_LYH7rEkkHlDMBdQGs-lmBjXRJIz2j9=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/yplNJstbgv4BEIT4dla4ZfHhj4aUr9XdyF6DKxR_LGXQokKnMrFeWjkOSuGeM52onZ7yzmuYXa1sdw7crcJZSbw=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/qq9CJe8yXnrKZdC347xnqz1x8eDLO4fJ0cZoOypTHcjCcm_VUQ0hBCDKo4mCFktGeq5iAtjHAY0paAo50P6R=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/hBhTArdNoIZ3Op6Fr9X9WBLP9gnkEIKLzg8CvnIcvFhJjcOYxGZGjT9ZtmGoKzQDuanJBQF0i6vnDjCO5Gp_Rw=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/Ro2RM3kqCEGSMKF7Zk7cpFpSaayMXzga02-Q7LWyP6WzY4_EwjteA8ffayh65fezFCiXSOtuIQz8OADatHqIEA=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/DrOYPQbdLc78fb9Excr5j7BsgZjWHyzlWiMGH9r0-ifhSegxHwVoi8OsXFeOZvnCHTi5VvemLw7RYwDPUHthxls=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Takano3D servers"
    },
    tags: ["MOD", "Free"],
    isRecommendation: false,
    isRecent: true
  },
    {
    id: "27",
    name: "LIMBO",
    slug: "limbo",
    developer: "Imaanshu N",
    rating: "4.6",
    downloads: "10k",
    size: "105 MB",
    version: "1.2.6",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/FJ8e7NYhyjzrjuROUSpigJ1TQNnZKUDh6AZc1SFjiD665bZsxr_7zus0DzlHIrC6Lgk=s150-rw",
   description: "LIMBO is an Indie game, with new gameplay and many layers of meaning in the plot. Let’s take a look at some interesting information about this game!",
    downloadUrl: "https://s1.1phut.io/v2/zpLN",
    videoUrls: ["https://youtube.com/watch?v=Y4HSyVXKYz8",
    "https://youtube.com/watch?v=2j7Id8S2IuQ"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/GaptorFLFNZRTHSaV4Wh3R4nnhnd_LCCW1fNIwLERCyNcI3X5LOlK3TxeCKZLeoZowE=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/mAQtHG90gFvktB5AkGhqPqZEW6s-Ghqql4Jq6_Az4Y2hqOl7JN5oDG3MNHJJEEr4Rg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/yxKadViR_JwU7Q5_s6OCEx3yU9WLR6Bo--kkkFThwUx5vNgxSPf3zbDDkjCWu_y0VQ=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/K1oLWUAPvUNSjbYQI4wHrDTwS2og0yDy5Hg2p2fCUlyOx9FchJzISBFyWj6Agip0Cms=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/Kj9lmcNbHpiaqJJLKvqwI9oPUKlO6Uqq0Alx5LjOZx7MrmCYA1JTQPtAO5FMpqUXcs2S=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/15Omhs7Wf3nNV0OL6SeAn7S-IL7_w0wRJjFcTWySrJWDXVnAWDvnepe44NtpdP4V-DRw=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/sMcfQtOUE_DgUOYY9vPVW6SCuAlwNSdbBcfmEMuNbjj9cFcAObSVV_06MOCMHNNJ_A=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/IJyIN5LH_WE9Wg8wurdKYH_mZZ3uZoc8qMIl4dcGAsorEDeSBnGGy7R9BW3VT_uwE4Q=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Takano3D servers"
    },
    tags: ["MOD", "Free"],
    isRecommendation: true,
    isRecent: true
  },
    {
    id: "28",
    name: "Rally Horizon",
    slug: "rally-horizon",
    developer: "Imaanshu N",
    rating: "4.1",
    downloads: "8k",
    size: "598 MB",
    version: "2.6.1",
    category: "Tools",
    type: "Game",
    updatedAt: "25/08/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/NFTKJsXIoh2CSxP77C_mrphziRG0MobZNL7sXqEdCuJlHBTUs-5NGBxn53d6S3iIvg=s150-rw",
   description: "Immersing yourself in the colorful neon racetrack in Rally Horizon, you will admire and master the wheel of dozens of attractive professional supercars. A racing game whose freshness and brilliance will keep your mood up all day.",
    downloadUrl: "https://s1.1phut.io/v2/8m0R",
    videoUrls: ["https://youtube.com/watch?v=6-A5YzWFoiw",
    "https://youtube.com/watch?v=tiViZPIlq2A"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/IPZDILteUSm5ufcTDQpD1OZaAjNswtZuFbOsRIThFXCgEYAE23T0PvkkgRefDAewBj0=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/FT3Lq8u5vCTVMx3qH_9ocYDS1i-JARag0-_QqSCCVQiV6kg6ZWPKwSluWjS8Re9LfQ=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/ZhGu3lW904wOqmOfZGot0z4JrID_smendZ8yqLcBLsIuVqgyiEizhkXrq_-3PAZNtg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/XYBTDyyPWgwApuBSy1Hsd_z9J8tmDBxmFc_4YOzATFMW1bb8LaV3JoBkXX53PzeMzC8=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/LPyhYncgzoI1ouYuWm_063uoI1cAxrvlsJfxVWdpubUoBzlU7lsNt_iR3wPuhQlq1_0=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/0B1zXALdKMyJyGaeASEyJqni9P4kJQ3nTywErUcnH7g_m7clE5GWGKIta0nlrO04Z5I=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Takano3D servers"
    },
    tags: ["MOD", "Free"],
    isRecommendation: true,
    isRecent: true
  },
    {
    id: "29",
    name: "Aurora Hills: Chapter 1",
    slug: "aurora-hills-chapter-1",
    developer: "Imaanshu N",
    rating: "4.9",
    downloads: "200k",
    size: "569 MB",
    version: "1.0.7",
    category: "Tools",
    type: "Game",
    updatedAt: "24/04/2026",
    icon: "https://static.apkmody.com/play-lh.googleusercontent.com/vyBSQFCniqisX061qDemtmTbeN6Xt0kCi5P0jNJJs3OybmhgICOOrHTnWtptpoPzJp4s=s150-rw",
   description: "Aurora Hills: Chapter 1 is a puzzle-adventure game with elements of horror and mystery. Developed and published by NovaSoft Interactive Ltd, a studio specializing in puzzle games, the game is set in Aurora Hills, a town in the Appalachian Mountains (USA), in 1981. The events in Aurora Hills: Chapter 1 begin with a series of mysterious disappearances that escalate in frequency. These disappearances leave no trace. You play as Ethan Hills, a park ranger working in the forest near Aurora Hills, investigating the disappearances to uncover the secrets hidden deep within the town.",
    downloadUrl: "https://s1.1phut.io/v2/QP17",
    videoUrls: ["https://youtube.com/watch?v=NsOV7eBWCfg"], // Converted to array support
    screenshots: [
      "https://static.apkmody.com/play-lh.googleusercontent.com/U579qG4z2QxnDqx2wW-q_PIkhGKbnVHbHXH4EHbSH0_omqaDzLSj-Zv5ZustS-21EZA=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/Ts8kwUhL1SjvmuoYdtW6u4Ul268yMiZN3WE2rOy3xE6wxAGbXnT7Jvs5LU0p6uzdkBM=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/ro_FFnSy-_Iwhixd1hz9NM_ga2kgcwvtMU_gYE2iPKcsUOACYf3uuUbaHqdmhupSUto=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/xqT1XRDo9rXJaLwG_hT6yo67tVkS8vGOtBhMQwXIM9X1u0KMnXBuSb1wZ9zPFmrR_g=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/_pJtcbj7pPYDbxNkg7MnIuR1ea6no1UD1-NzhvdHaPzhzxDj4nAcZG-KFgQVs1EXxDCa=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/NEGaO2Tlwtix1vuaqatA7eQMiTAB_lVye8xzjyYltX-PPVyLizIeb-EPcm7om6wNUUs=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/f6DPhYxK-C4swSCNAE7WH2pDblrPoGIem3-0LcGwYLBtKtWSfCfWFb_1NXELdA_krDg=-rw",
      "https://static.apkmody.com/play-lh.googleusercontent.com/zRnnDPPgFPLKM8F709x-TAdvbnXWw2_wMyhPXR6qNfXOB3F4HLZ3s_TbYlbtqPSjQ9Za=-rw",
    ],
    security: {
      checksum: "SHA-256: 91yeb72te8wg8w9sg6euw8hw7wh8w",
      secureToken: "Secure accounts without ban risk",
      cloudStorage: "Direct connection to Moviebox servers"
    },
    tags: ["MOD", "Long Line", "Free"],
    isRecommendation: false,
    isRecent: true
  }
  
];

export const CATEGORIES_DATA: CategoryItem[] = BASE_CATEGORIES.map(category => {
  const appsCount = APPS_DATA.filter(app => app.category === category.name).length;
  return {
    ...category,
    count: appsCount
  };
});

export const BLOG_POSTS: BlogPost[] = [
  {
  id: "b1",
  title: "CEO of a Takano3D company",
  summary: "An exclusive look into the vision, mobile development journey, and independent ecosystem behind Takano3D.",
  content: "As the founder and lead engineer of Takano3D, every architecture, script, and application layout is built entirely from a mobile workflow. From web infrastructure and modding ecosystems to creating seamless user experiences, this is the story of pushing mobile development limits without relying on a PC.",
  image: "https://6a900b5efbbe2019f0957b40.imgix.net/sandbox/1000043555.png?auto=format&dpr=1",
  date: "11 July, 2026",
  author: "Takano3D"
  },
  {
    id: "b2",
    title: "Top 5 Android MODs of the Month",
    summary: "Discover modified apps and games with the most outstanding features unlocked completely free of charge.",
    content: "Android stands out over other mobile ecosystems for its versatility and freedom of installation. In this article, we delve into five exceptional modifications that will allow you to optimize your applications and expand your entertainment limits. From Spotify Premium to professional video editors without watermarks, we explain how to install them safely on your smartphone using the clean and pre-verified files available on Look Mod Store.",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    date: "11 July, 2026",
    author: "Takano3D"
  },
  {
    id: "b3",
    title: "How to Safely Install an APK / OBB File",
    summary: "Step-by-step guide for beginners and advanced users on how to enable unknown sources without compromising your phone.",
    content: "Manual installation of APK files is a simple task but requires attention to certain critical security details. First, you must go to Settings > Security and enable 'Install applications from unknown sources'. In this guide, we show you how to use our integrated SHA-256 validator to confirm that no files have been tampered with, protecting your personal information at all times.",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80",
    date: "08 July, 2026",
    author: "Takano3D Team"
  }
];
